version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: voicenote-app:latest
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/workspace
      - media:/workspace/media
    working_dir: /workspace
    command: bash -lc "python manage.py migrate && gunicorn voicenote_backend.wsgi:application --bind 0.0.0.0:8000 --workers 2"
    expose:
      - "8000"
    depends_on:
      - ffmpeg

  ffmpeg:
    image: jrottenberg/ffmpeg:6.1-ubuntu
    command: ["-version"]
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  media:

